import type { MenuItem } from "./types";

export const MENU: MenuItem[] = [
  {
    id: "signature-jollof",
    name: "DreamTable Signature Jollof",
    description:
      "Smoky party-style jollof rice served with grilled chicken and house sauce.",
    price: 8500,
    category: "rice",
    image: "/food/jollof.jpg",
    spice: 2,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: [
      "Long-grain rice",
      "Smoked tomatoes",
      "Scotch bonnet",
      "Thyme",
      "Bay leaf",
      "Grilled chicken",
      "House sauce",
    ],
    signature: 1,
    customizable: true,
  },
  {
    id: "suya-fries",
    name: "Suya Loaded Fries",
    description:
      "Crispy fries topped with spicy suya beef, onions and DreamTable signature sauce.",
    price: 7000,
    category: "sides",
    image: "/food/suya-fries.jpg",
    spice: 2,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: ["Fries", "Suya beef", "Peanut spice", "Red onions", "House sauce"],
    signature: 2,
    customizable: true,
  },
  {
    id: "creamy-pasta",
    name: "Creamy Chicken Pasta",
    description: "Creamy garlic pasta with grilled chicken, parmesan and herbs.",
    price: 9000,
    category: "pasta",
    image: "/food/pasta.jpg",
    spice: 0,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: ["Pasta", "Cream", "Garlic", "Grilled chicken", "Parmesan", "Herbs"],
    signature: 3,
    customizable: true,
  },
  {
    id: "fire-chicken",
    name: "Fire-Grilled Chicken",
    description: "Charcoal grilled chicken marinated in DreamTable's secret pepper blend.",
    price: 8000,
    category: "grills",
    image: "/food/chicken.jpg",
    spice: 2,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: ["Chicken", "Pepper marinade", "Thyme", "Ginger", "Garlic", "Charcoal"],
    signature: 4,
    customizable: true,
  },
  {
    id: "beef-burger",
    name: "DreamTable Beef Burger",
    description:
      "Double smashed beef patties, melted cheese, caramelised onions and house sauce.",
    price: 9500,
    category: "burgers",
    image: "/food/burger.jpg",
    spice: 1,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: [
      "Beef patties",
      "Cheddar",
      "Caramelised onions",
      "Brioche",
      "House sauce",
    ],
    signature: 5,
    customizable: true,
  },
  {
    id: "seafood-rice",
    name: "Seafood Pepper Rice",
    description: "Aromatic pepper rice with prawns, calamari and grilled vegetables.",
    price: 12000,
    category: "rice",
    image: "/food/seafood.jpg",
    spice: 3,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: ["Pepper rice", "Prawns", "Calamari", "Grilled vegetables", "Scotch bonnet"],
    signature: 6,
    customizable: true,
  },
  {
    id: "chocolate",
    name: "Chocolate Indulgence",
    description: "Warm chocolate dessert with vanilla cream and chocolate crumble.",
    price: 5500,
    category: "desserts",
    image: "/food/chocolate.jpg",
    spice: 0,
    popular: true,
    vegetarian: true,
    available: true,
    ingredients: ["Dark chocolate", "Vanilla cream", "Butter", "Sugar", "Cacao crumble"],
    signature: 7,
    customizable: false,
  },
  {
    id: "ofada",
    name: "Ofada Rice & Ayamase",
    description: "Local ofada rice with rich green ayamase stew and assorted meats.",
    price: 9000,
    category: "rice",
    image: "/food/ofada.jpg",
    spice: 3,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: ["Ofada rice", "Green pepper stew", "Assorted meats", "Locust beans"],
    customizable: true,
  },
  {
    id: "coconut-fried-rice",
    name: "Coconut Fried Rice",
    description: "Fragrant coconut fried rice with vegetables, shrimp and a squeeze of lime.",
    price: 7500,
    category: "rice",
    image: "/food/jollof.jpg",
    spice: 1,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Rice", "Coconut milk", "Shrimp", "Carrots", "Peas", "Lime"],
    customizable: true,
  },
  {
    id: "native-jollof",
    name: "Native Palm Jollof",
    description: "Palm-oil jollof with smoked fish, ugu and a slow-cooked pepper base.",
    price: 8000,
    category: "rice",
    image: "/food/ofada.jpg",
    spice: 2,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Rice", "Palm oil", "Smoked fish", "Ugu", "Peppers"],
    customizable: true,
  },
  {
    id: "suya-platter",
    name: "Suya Platter",
    description: "Charcoal suya beef, peanut spice, onions and tomatoes — made to share.",
    price: 11000,
    category: "grills",
    image: "/food/suya-fries.jpg",
    spice: 3,
    popular: true,
    vegetarian: false,
    available: true,
    ingredients: ["Beef", "Suya spice", "Onions", "Tomatoes", "Cabbage"],
    customizable: true,
  },
  {
    id: "grilled-fish",
    name: "Fire Tilapia",
    description: "Whole grilled tilapia with pepper sauce, lemon and garden herbs.",
    price: 10500,
    category: "grills",
    image: "/food/seafood.jpg",
    spice: 2,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Tilapia", "Pepper sauce", "Lemon", "Ginger", "Garlic"],
    customizable: true,
  },
  {
    id: "asun",
    name: "Asun",
    description: "Peppered grilled goat, chopped hot, finished with onions at the pass.",
    price: 9500,
    category: "grills",
    image: "/food/chicken.jpg",
    spice: 3,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Goat", "Scotch bonnet", "Onions", "Thyme"],
    customizable: true,
  },
  {
    id: "jollof-pasta",
    name: "Jollof Pasta",
    description: "Our jollof sauce, tossed through penne, with grilled chicken.",
    price: 8500,
    category: "pasta",
    image: "/food/pasta.jpg",
    spice: 2,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Penne", "Jollof sauce", "Chicken", "Thyme"],
    customizable: true,
  },
  {
    id: "seafood-alfredo",
    name: "Seafood Alfredo",
    description: "Silky garlic cream pasta with prawns and calamari.",
    price: 11500,
    category: "pasta",
    image: "/food/pasta.jpg",
    spice: 0,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Pasta", "Prawns", "Calamari", "Cream", "Garlic", "Parmesan"],
    customizable: true,
  },
  {
    id: "suya-burger",
    name: "Suya Chicken Burger",
    description: "Grilled chicken, suya spice, pickled onions and cool yoghurt sauce.",
    price: 8500,
    category: "burgers",
    image: "/food/burger.jpg",
    spice: 2,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Chicken", "Suya spice", "Brioche", "Yoghurt sauce", "Onions"],
    customizable: true,
  },
  {
    id: "plantain-smash",
    name: "Plantain Smash",
    description: "Crisp plantain, black-bean patty, avocado and pepper relish.",
    price: 8000,
    category: "burgers",
    image: "/food/burger.jpg",
    spice: 1,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Plantain", "Black beans", "Avocado", "Pepper relish", "Brioche"],
    customizable: true,
  },
  {
    id: "dodo",
    name: "Fried Plantain",
    description: "Ripe plantain, fried until the edges caramelise.",
    price: 2500,
    category: "sides",
    image: "/food/ofada.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Ripe plantain", "Sea salt"],
    customizable: false,
  },
  {
    id: "coleslaw",
    name: "House Coleslaw",
    description: "Cabbage, carrot and a light mustard cream.",
    price: 2000,
    category: "sides",
    image: "/food/pasta.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Cabbage", "Carrot", "Mustard", "Cream"],
    customizable: false,
  },
  {
    id: "moi-moi",
    name: "Moi Moi",
    description: "Steamed bean pudding with peppers and a boiled egg.",
    price: 3000,
    category: "sides",
    image: "/food/ofada.jpg",
    spice: 1,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Honey beans", "Peppers", "Onions", "Egg"],
    customizable: false,
  },
  {
    id: "gizzard",
    name: "Peppered Gizzard",
    description: "Tender gizzard in a glossy pepper sauce.",
    price: 4500,
    category: "sides",
    image: "/food/chicken.jpg",
    spice: 2,
    popular: false,
    vegetarian: false,
    available: true,
    ingredients: ["Gizzard", "Pepper sauce", "Onions"],
    customizable: true,
  },
  {
    id: "chapman",
    name: "Chapman",
    description: "The Lagos classic — cucumber, orange, grenadine, very cold.",
    price: 2500,
    category: "drinks",
    image: "/food/hero.jpg",
    spice: 0,
    popular: true,
    vegetarian: true,
    available: true,
    ingredients: ["Cucumber", "Orange", "Grenadine", "Fizz", "Angostura"],
    customizable: false,
  },
  {
    id: "zobo",
    name: "Zobo",
    description: "Hibiscus, ginger and lime, brewed in-house.",
    price: 2000,
    category: "drinks",
    image: "/food/hero.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Hibiscus", "Ginger", "Lime", "Pineapple"],
    customizable: false,
  },
  {
    id: "orange",
    name: "Fresh Orange",
    description: "Pressed to order. No concentrate.",
    price: 2500,
    category: "drinks",
    image: "/food/hero.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Oranges"],
    customizable: false,
  },
  {
    id: "soft-drink",
    name: "Cold Soft Drink",
    description: "Coke, Fanta, Sprite or Malt — ask for your usual.",
    price: 1500,
    category: "drinks",
    image: "/food/hero.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Your choice of bottled soft drink"],
    customizable: false,
  },
  {
    id: "palm-wine",
    name: "Palm Wine Cooler",
    description: "Lightly sparkling palm wine, citrus, served over ice.",
    price: 3500,
    category: "drinks",
    image: "/food/hero.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Palm wine", "Citrus", "Ice"],
    customizable: false,
  },
  {
    id: "puff-puff",
    name: "Puff Puff & Cream",
    description: "Warm puff puff, vanilla ice cream, honey.",
    price: 4000,
    category: "desserts",
    image: "/food/chocolate.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Dough", "Vanilla ice cream", "Honey"],
    customizable: false,
  },
  {
    id: "coconut-cake",
    name: "Coconut Cake",
    description: "Soft coconut crumb, toasted flakes, a little cream.",
    price: 4500,
    category: "desserts",
    image: "/food/chocolate.jpg",
    spice: 0,
    popular: false,
    vegetarian: true,
    available: true,
    ingredients: ["Coconut", "Flour", "Cream", "Sugar"],
    customizable: false,
  },
];

export const SIGNATURES = MENU.filter((item) => item.signature).sort(
  (a, b) => (a.signature ?? 0) - (b.signature ?? 0),
);
