import type { Address, LoyaltyEvent, Order, Profile, Reservation } from "./types";

export const DEFAULT_PROFILE: Profile = {
  name: "Adaeze Okonkwo",
  phone: "+234 803 441 2290",
  email: "adaeze@email.com",
};

export const DEFAULT_ADDRESSES: Address[] = [
  {
    id: "home",
    label: "Home",
    line: "12 Admiralty Road, Lekki Phase 1, Lagos",
    apartment: "Apartment 4B",
  },
  {
    id: "work",
    label: "Work",
    line: "The Wings Tower, 17A Ozumba Mbadiwe, Victoria Island",
    apartment: "Reception",
  },
];

const PICKUP_ADDRESS = "14 Adeola Odeku Street, Victoria Island, Lagos";

function ago(minutes: number) {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

export const SEED_ORDERS: Order[] = [
  {
    id: "DT2847",
    items: [
      {
        lineId: "seed-1",
        menuItemId: "signature-jollof",
        name: "DreamTable Signature Jollof",
        image: "/food/jollof.jpg",
        unitPrice: 8500,
        quantity: 1,
        protein: "chicken",
        extras: ["plantain"],
        spice: "medium",
      },
      {
        lineId: "seed-2",
        menuItemId: "suya-fries",
        name: "Suya Loaded Fries",
        image: "/food/suya-fries.jpg",
        unitPrice: 7000,
        quantity: 1,
        extras: [],
        spice: "hot",
      },
      {
        lineId: "seed-3",
        menuItemId: "chapman",
        name: "Chapman",
        image: "/food/hero.jpg",
        unitPrice: 2500,
        quantity: 2,
        extras: [],
      },
    ],
    status: "out-for-delivery",
    fulfillment: "delivery",
    customer: {
      name: "Adaeze Okonkwo",
      phone: "+234 803 441 2290",
      address: "12 Admiralty Road, Lekki Phase 1, Lagos",
      apartment: "Apartment 4B",
      instructions: "Call when outside.",
    },
    payment: "card",
    subtotal: 20500,
    deliveryFee: 1500,
    discount: 2050,
    total: 19950,
    promoCode: "DREAM10",
    createdAt: ago(18),
    etaMinutes: 28,
    rider: { name: "Daniel", vehicle: "Motorbike", phone: "+234 809 221 0044" },
    pointsEarned: 199,
  },
  {
    id: "DT2831",
    items: [
      {
        lineId: "seed-4",
        menuItemId: "beef-burger",
        name: "DreamTable Beef Burger",
        image: "/food/burger.jpg",
        unitPrice: 9500,
        quantity: 2,
        extras: ["fries"],
        spice: "mild",
      },
    ],
    status: "delivered",
    fulfillment: "delivery",
    customer: {
      name: "Femi Olatunji",
      phone: "+234 802 118 3340",
      address: "8 Banana Island Road, Ikoyi",
      apartment: "Gate 2",
      instructions: "Leave with reception.",
    },
    payment: "transfer",
    subtotal: 22000,
    deliveryFee: 1500,
    discount: 0,
    total: 23500,
    createdAt: ago(140),
    etaMinutes: 32,
    rider: { name: "Tunde", vehicle: "Motorbike", phone: "+234 701 992 1103" },
    pointsEarned: 235,
  },
  {
    id: "DT2822",
    items: [
      {
        lineId: "seed-5",
        menuItemId: "seafood-rice",
        name: "Seafood Pepper Rice",
        image: "/food/seafood.jpg",
        unitPrice: 12000,
        quantity: 1,
        extras: [],
        spice: "hot",
        protein: "prawns",
      },
    ],
    status: "preparing",
    fulfillment: "pickup",
    customer: {
      name: "Amaka Obi",
      phone: "+234 810 445 7781",
      address: PICKUP_ADDRESS,
      apartment: "",
      instructions: "",
    },
    payment: "cash",
    subtotal: 12000,
    deliveryFee: 0,
    discount: 0,
    total: 12000,
    createdAt: ago(22),
    etaMinutes: 20,
    pointsEarned: 120,
  },
  {
    id: "DT2818",
    items: [
      {
        lineId: "seed-6",
        menuItemId: "fire-chicken",
        name: "Fire-Grilled Chicken",
        image: "/food/chicken.jpg",
        unitPrice: 8000,
        quantity: 1,
        extras: ["coleslaw", "plantain"],
        spice: "extra-hot",
      },
    ],
    status: "confirmed",
    fulfillment: "delivery",
    customer: {
      name: "Tolu Adewale",
      phone: "+234 809 332 1904",
      address: "22 Admiralty Way, Lekki",
      apartment: "House 6",
      instructions: "Buzzer 6.",
    },
    payment: "card",
    subtotal: 10500,
    deliveryFee: 1500,
    discount: 0,
    total: 12000,
    createdAt: ago(8),
    etaMinutes: 35,
    pointsEarned: 120,
  },
  {
    id: "DT2804",
    items: [
      {
        lineId: "seed-7",
        menuItemId: "creamy-pasta",
        name: "Creamy Chicken Pasta",
        image: "/food/pasta.jpg",
        unitPrice: 9000,
        quantity: 1,
        extras: [],
      },
      {
        lineId: "seed-8",
        menuItemId: "chocolate",
        name: "Chocolate Indulgence",
        image: "/food/chocolate.jpg",
        unitPrice: 5500,
        quantity: 1,
        extras: [],
      },
    ],
    status: "delivered",
    fulfillment: "delivery",
    customer: {
      name: "Chioma Eze",
      phone: "+234 703 229 8811",
      address: "15 Karimu Kotun, Victoria Island",
      apartment: "Flat 2",
      instructions: "",
    },
    payment: "card",
    subtotal: 14500,
    deliveryFee: 1500,
    discount: 0,
    total: 16000,
    createdAt: ago(2600),
    etaMinutes: 30,
    pointsEarned: 160,
  },
];

export const SEED_RESERVATIONS: Reservation[] = [
  {
    id: "DT4812",
    name: "Adaeze Okonkwo",
    phone: "+234 803 441 2290",
    email: "adaeze@email.com",
    date: "2026-10-16",
    time: "19:30",
    guests: 4,
    occasion: "dinner",
    request: "Window table if possible.",
    status: "confirmed",
    createdAt: ago(2400),
  },
  {
    id: "DT4810",
    name: "Ibrahim Bello",
    phone: "+234 806 441 9002",
    email: "ibrahim@email.com",
    date: "2026-10-02",
    time: "20:00",
    guests: 2,
    occasion: "date-night",
    request: "",
    status: "confirmed",
    createdAt: ago(400),
  },
  {
    id: "DT4804",
    name: "Ngozi Umeh",
    phone: "+234 701 228 3345",
    email: "ngozi@email.com",
    date: "2026-10-02",
    time: "19:00",
    guests: 6,
    occasion: "birthday",
    request: "A small cake after mains.",
    status: "pending",
    createdAt: ago(90),
  },
  {
    id: "DT4798",
    name: "David Mensah",
    phone: "+234 802 991 0044",
    email: "david@email.com",
    date: "2026-10-09",
    time: "13:00",
    guests: 3,
    occasion: "business",
    request: "Quiet corner.",
    status: "confirmed",
    createdAt: ago(1800),
  },
];

export const SEED_LOYALTY: LoyaltyEvent[] = [
  { id: "l1", label: "Order #DT2804", points: 160, at: ago(2600) },
  { id: "l2", label: "Order #DT2847", points: 199, at: ago(18) },
  { id: "l3", label: "Welcome to The Circle", points: 881, at: ago(8000) },
];

export const REVIEWS = [
  {
    quote: "Honestly, that jollof should be illegal.",
    name: "Tolu A.",
    dish: "Signature Jollof",
    image: "/food/jollof.jpg",
  },
  {
    quote: "Ordered at 7:42 and it arrived before 8:20. Still hot.",
    name: "Femi O.",
    dish: "Fire-Grilled Chicken",
    image: "/food/chicken.jpg",
  },
  {
    quote: "The suya fries are officially my personality now.",
    name: "Amaka O.",
    dish: "Suya Loaded Fries",
    image: "/food/suya-fries.jpg",
  },
  {
    quote: "Came for dinner. Left planning the next one in the car.",
    name: "Kemi B.",
    dish: "Seafood Pepper Rice",
    image: "/food/seafood.jpg",
  },
];
